//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ApartmentDBContext : DbContext
    {
        public ApartmentDBContext()
            : base("name=ApartmentDBContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblAddress> tblAddresses { get; set; }
        public virtual DbSet<tblAmenity> tblAmenities { get; set; }
        public virtual DbSet<tblApartment> tblApartments { get; set; }
        public virtual DbSet<tblBookingDetail> tblBookingDetails { get; set; }
        public virtual DbSet<tblFinalRentAfterDiscount> tblFinalRentAfterDiscounts { get; set; }
        public virtual DbSet<tblOwner> tblOwners { get; set; }
        public virtual DbSet<tblOwnerReview> tblOwnerReviews { get; set; }
        public virtual DbSet<tblOwnerVerification> tblOwnerVerifications { get; set; }
        public virtual DbSet<tblRent> tblRents { get; set; }
        public virtual DbSet<tblTenant> tblTenants { get; set; }
        public virtual DbSet<tblTenantReview> tblTenantReviews { get; set; }
        public virtual DbSet<tblTenantVerification> tblTenantVerifications { get; set; }
    }
}
