//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblApartment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblApartment()
        {
            this.tblAmenities = new HashSet<tblAmenity>();
            this.tblRents = new HashSet<tblRent>();
        }
    
        public int apartment_ID { get; set; }
        public string apartment_address { get; set; }
        public Nullable<int> apartment_NumberOfRooms { get; set; }
        public string apartment_DescriptionOfRoom { get; set; }
        public Nullable<int> apartment_PriceOfRoom { get; set; }
        public Nullable<bool> apartment_IsRoomAvailable { get; set; }
        public int apartment_OwnerID { get; set; }
        public string apartment_Photos { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblAmenity> tblAmenities { get; set; }
        public virtual tblFinalRentAfterDiscount tblFinalRentAfterDiscount { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblRent> tblRents { get; set; }
        public virtual tblOwner tblOwner { get; set; }
    }
}
