//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblBookingDetail
    {
        public int booking_ID { get; set; }
        public Nullable<System.DateTime> booking_BookingDate { get; set; }
        public Nullable<System.DateTime> booking_MoveInDate { get; set; }
        public Nullable<System.DateTime> booking_MoveOutDate { get; set; }
        public int booking_TenantID { get; set; }
        public int booking_OwnerID { get; set; }
        public int booking_ApartmentID { get; set; }
    
        public virtual tblOwner tblOwner { get; set; }
        public virtual tblTenant tblTenant { get; set; }
    }
}
