//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblOwner
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblOwner()
        {
            this.tblApartments = new HashSet<tblApartment>();
            this.tblBookingDetails = new HashSet<tblBookingDetail>();
            this.tblOwnerReviews = new HashSet<tblOwnerReview>();
            this.tblOwnerVerifications = new HashSet<tblOwnerVerification>();
        }
    
        public int owner_ID { get; set; }
        public string owner_UserName { get; set; }
        public string owner_FirstName { get; set; }
        public string owner_LastName { get; set; }
        public Nullable<int> owner_age { get; set; }
        public string owner_Email { get; set; }
        public string owner_password { get; set; }
        public Nullable<int> owner_telephone { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblApartment> tblApartments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblBookingDetail> tblBookingDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblOwnerReview> tblOwnerReviews { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblOwnerVerification> tblOwnerVerifications { get; set; }
    }
}
