//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblRent
    {
        public int rent_RentID { get; set; }
        public int rent_ApartmentID { get; set; }
        public int rent_Rent { get; set; }
        public int rent_Deposit { get; set; }
        public Nullable<int> rent_Discount { get; set; }
    
        public virtual tblApartment tblApartment { get; set; }
    }
}
