//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTenant
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblTenant()
        {
            this.tblBookingDetails = new HashSet<tblBookingDetail>();
            this.tblTenantReviews = new HashSet<tblTenantReview>();
            this.tblTenantVerifications = new HashSet<tblTenantVerification>();
        }
    
        public int tenant_ID { get; set; }
        public string tenant_UserName { get; set; }
        public string tenant_FirstName { get; set; }
        public string tenant_LastName { get; set; }
        public Nullable<int> tenant_age { get; set; }
        public string tenant_Email { get; set; }
        public string tenant_password { get; set; }
        public Nullable<int> tenant_telephone { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblBookingDetail> tblBookingDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblTenantReview> tblTenantReviews { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblTenantVerification> tblTenantVerifications { get; set; }
    }
}
