//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTenantReview
    {
        public int review_ReviewNumber { get; set; }
        public int review_TenantID { get; set; }
        public int review_ApartmentID { get; set; }
        public int review_OwnerID { get; set; }
        public string review_ApartmentReview { get; set; }
    
        public virtual tblTenant tblTenant { get; set; }
    }
}
