//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTenantVerification
    {
        public int tenant_VerificationID { get; set; }
        public Nullable<int> tenant_TenantID { get; set; }
        public string tenant_TenantDocument { get; set; }
    
        public virtual tblTenant tblTenant { get; set; }
    }
}
